name: Draft Release

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - run: |
          cd 01-release-and-auto-update
          pnpm install
          pnpm run release
        env:
          GH_TOKEN: ${{ github.token }}
